insert into team(id, name) values
	('fcba', 'FC Blešno A'),
	('fcbb', 'FC Blešno B'),
	('fcbf', 'FC Blešno F'),
	('ujza', '1. FK Újezd'),
	('rsca', '1. RSC Hradec Králové'),
	('aera', 'AC Aero'),
	('bfka', 'BFK Orel HK A'),
	('bfkb', 'BFK Orel HK B'),
	('bfkc', 'BFK Orel HK C'),
	('blaa', 'Blasters'),
	('bufa', 'Buffalo'),
	('cama', 'Camelot'),
	('cana', 'Cannibals'),
	('czma', 'CzechMill'),
	('hesa', 'FC Hespro'),
	('koja', 'FC Kojot'),
	('sana', 'FC Santus Dobruška'),
	('flmb', 'Flamengo HK B'),
	('frdb', 'Frantic Dogs HK B'),
	('gala', 'Galaxy Juniors'),
	('giga', 'Gigantes'),
	('hroa', 'Hrobníci 09'),
	('hura', 'Hurican/Bruggy'),
	('infa', 'Infarkt'),
	('inta', 'Internacionale'),
	('joka', 'Jokerit'),
	('lega', 'Legia HK A'),
	('legb', 'Legia HK B'),
	('nkla', 'Nebeský klády'),
	('nxta', 'Next'),
	('nkga', 'NK Growl'),
	('pana', 'FC Panthers'),
	('pena', 'Penalta'),
	('piva', 'Pivrnci'),
	('poha', 'Pohoda Seniors'),
	('rapa', 'Rapid'),
	('reda', 'Reds HK'),
	('rlha', 'SK FOSP Rešetova Lhota'),
	('repa', 'Penguins/Replacement'),
	('rmta', 'RMT Argentinos Všestary'),
	('sena', 'Senior'),
	('seva', 'Severka'),
	('snoa', 'Šnorchl'),
	('stra', 'Štroncek Cerekvice'),
	('lgna', 'The Legends'),
	('vlca', 'Vlčáci'),
	('uhka', 'Votroci z UHK'),
	('vesa', 'Veselá Šatna');
	
insert into team(id, name) values
	('suma', 'Celá sezóna');